//
// Created by Tayyab on 13/11/2023.
//

#ifndef HOSPITAL_PROJECT_FATIMANOORAMBULANCE_H
#define HOSPITAL_PROJECT_FATIMANOORAMBULANCE_H
void ambulance();
#endif //HOSPITAL_PROJECT_FATIMANOORAMBULANCE_H
